// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
)

type Session struct {
	Token     string
	UserID    int64
	ExpiresAt int64
}

type Task struct {
	ID          int64
	UserID      int64
	CreatedAt   int64
	Category    int64
	Text        string
	CompletedAt sql.NullInt64
	Foreign     interface{}
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    int64
}
