// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"database/sql"
)

type Session struct {
	Token     string
	UserID    int64
	ExpiresAt string
}

type Task struct {
	ID          int64
	UserID      int64
	CreatedAt   string
	Category    int64
	Text        string
	CompletedAt sql.NullString
	Foreign     interface{}
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    string
}
